### ISSUE TITLE
Wrong validation in example 3.3.1 if statement

### ISSUE THREAD

**Issue by BlackJair** [conversational-interfaces/dms#3]
Following the _Getting Started_ I found an error in a validation:
```
once {
  number = 1
}

if number > 2 {
  act "Number is greater than or equal to 2."
}
else {
  act "Number is less than 2."
}

number = number + 1
```

The text "Number is greater than or equal to 2" will always be wrong, the if statement should be _number >= 2_.

**Comment by pudg** [comment]
Hi @BlackJair, 

We really appreciate you taking the time to point this out. The issue has been addressed in [this commit](https://github.com/w3c/dms/commit/ff6d6647e5c98d7b0feda0d75c74d2874c7edef7?diff=split#diff-eacf331f0ffc35d4b482f1d15a887d3bL246) however the official report has not yet been updated with the latest changes.
